# load packages
import pandas as pd
import re

# container version of workflow
containerized: "docker://milesroberts/slim-sweep-cnn"

# load config file
configfile: "../config/config.yaml"

# load samples
parameters = pd.read_table("../config/parameters.tsv", sep="\t", dtype={"ID": str}).set_index(["ID"], drop=False)

# execute very simple rules on local machine
localrules: all, all_per_sim

wildcard_constraints:
    ID="[a-zA-Z0-9]+"

# gather all images for training CNN
rule all:
    input:
        #expand("data/images/slim_{ID}.png", ID=parameters.index.get_level_values("ID")),
        expand("finished/{ID}.done", ID=parameters.index.get_level_values("ID")),
        #"fixation_times.txt",
        #"sweep_ages.txt"

rule all_per_sim:
    input:
        expand("images/{{ID}}_{n}_{m}.png", n = config["n"], m = config["m"]),
        expand("sweep_stats/{{ID}}_{n}_{m}.tsv", n = config["n"], m = config["m"])
    output:
        touch("finished/{ID}.done")

include: "rules/slim.smk"
#include: "rules/create_image.smk"
#include: "rules/sweep_stats.smk"
include: "rules/extract_log_data.smk"
