# load packages
import pandas as pd
import re

# load config file
configfile: "../config/config.yaml"
print(config)

# load samples
parameters = pd.read_table("../config/parameters.tsv", sep="\t", dtype={"ID": str}).set_index(["ID"], drop=False)

# gather all images for training CNN
rule all:
	input:
		#["data/images/slim_{ID}.png".format(ID=ID) for ID in range(1,config["K"] + 1)],
		#expand("data/tables/slim_{ID}.table", ID=parameters.index.get_level_values("ID"))
		expand("data/images/slim_{ID}.png", ID=parameters.index.get_level_values("ID")),
		"fixation_times.txt",
		"sweep_ages.txt"
		#expand("slim_{ID}.tsv", ID=parameters.index.get_level_values("ID"))
		#"best_cnn.h5",
		


include: "rules/slim.smk"
include: "rules/create_image.smk"
include: "rules/sweep_stats.smk"
include: "rules/extract_log_data.smk"
#include: "rules/sample_params.smk"
#include: "rules/fit_cnn.smk"
