usage:
  software-stack-deployment:
    conda: true # whether pipeline works with '--sdm conda'
    apptainer: false # whether pipeline works with '--sdm apptainer/singularity'
    apptainer+conda: true # whether pipeline works with '--sdm conda apptainer/singularity'
    report: false # whether creation of reports using 'snakemake --report report.zip' is supported
