# Workflow parameters

# number of simulations to run
K: 50000

# Dimmension of images will be nidv*nloc*3
# Number of individual genomes to sample
nidv: 128

# Number of loci to sample
nloc: 128

# Measurement of genetic distance between loci
distMethod: "manhattan"

# method for clustering genomes based on genetic distance
clustMethod: "complete"

# demographic pattern if using logistic demography
# options: constant, growth, decay, cycle, chaos, custom
demography: "custom"
