executor: slurm
jobs: 975
cores: 975

# use sensible defaults for your cluster
default-resources:
    slurm_account: "josephsnodes"
    slurm_partition: "josephsnodes"
    mem_mb_per_cpu: 8000
    cpus_per_task: 1
    runtime: "239m"

# here only rules, which require different (more) resources:
#set-resources:

# parallelization with threads needs to be defined separately:
# threads and cpus_per_task are supposed to be synonymous for this plugin, but for some reason I need to specify them separately
#set-threads:
