# snakemake arguments
executor: slurm
jobs: unlimited
cores: all
max-jobs-per-timespan: 1000/1s
scheduler-subsample: 100000

# rules to execute locally, because they're too fast to bother with cluster submission
# localrules: all_one_pops, all_two_pops, all

# use sensible defaults for your cluster
default-resources:
    slurm_account: "co_moilab"
    slurm_partition: "savio2_htc"
    slurm_qos: "savio_lowprio"
    ntasks: 1
    cpus_per_task: 1
    runtime: "10m"
    mem_mb: 0

# here only rules, which require different (more) resources:
#set-resources:

# parallelization with threads needs to be defined separately:
# threads and cpus_per_task are supposed to be synonymous for this plugin, but for some reason I need to specify them separately
#set-threads:
